PUT http://localhost:24110/api/v1.0/creators
Content-Type: application/json

{
  "id": 81,
  "login": "updatedCreator4087",
  "password": "updatedAsdfghj9507",
  "firstname": "updatedFirstname1401",
  "lastname": "updatedLastname7182"
}
