# Generated by Django 4.2.11 on 2024-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
