# Generated by Django 4.2.11 on 2024-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0002_alter_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
