# Generated by Django 4.2.11 on 2024-03-20 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0005_alter_issue_created_alter_issue_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 3, 55, 211488)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 3, 55, 211488)),
        ),
    ]
