# Generated by Django 4.2.11 on 2024-03-20 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0006_alter_issue_created_alter_issue_modified'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='unique_migration_host_combination',
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 9, 6, 197560)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 9, 6, 197560)),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('id', 'title')},
        ),
    ]
