# Generated by Django 4.2.11 on 2024-03-20 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0007_remove_issue_unique_migration_host_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 19, 55, 412246)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 19, 55, 412246)),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2048)),
                ('issueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rw_lab1.issue')),
            ],
        ),
    ]
