# Generated by Django 4.2.11 on 2024-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0008_alter_issue_created_alter_issue_modified_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('issues', models.ManyToManyField(to='rw_lab1.issue')),
            ],
        ),
    ]
