# Generated by Django 4.2.11 on 2024-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0010_alter_issue_created_alter_issue_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='login',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
