# Generated by Django 4.2.11 on 2024-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0011_alter_creator_login_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
