# Generated by Django 4.2.11 on 2024-03-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rw_lab1', '0012_alter_issue_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creator',
            table='tbl_creator',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='tbl_issue',
        ),
        migrations.AlterModelTable(
            name='note',
            table='tbl_note',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tbl_tag',
        ),
    ]
