CREATE TABLE distcomp.tbl_editors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text UNIQUE NOT NULL CHECK (LENGTH(login) BETWEEN 2 AND 64),
    password text NOT NULL CHECK (LENGTH(password) BETWEEN 8 AND 128),
    firstname text NOT NULL CHECK (LENGTH(firstname) BETWEEN 2 AND 64),
    lastname text NOT NULL CHECK (LENGTH(lastname) BETWEEN 2 AND 64)
);

CREATE TABLE distcomp.tbl_stories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "editorId" bigint NOT NULL REFERENCES distcomp.tbl_editors(id),
    title text UNIQUE NOT NULL CHECK (LENGTH(title) BETWEEN 2 AND 64),
    content text NOT NULL CHECK (LENGTH(content) BETWEEN 4 AND 2048),
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE distcomp.tbl_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "storyId" bigint NOT NULL REFERENCES distcomp.tbl_stories(id),
    content text NOT NULL CHECK (LENGTH(content) BETWEEN 2 AND 2048)
);

CREATE TABLE distcomp.tbl_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL CHECK (LENGTH(name) BETWEEN 2 AND 32)
);

CREATE TABLE distcomp.tbl_stories_m2m_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "storyId" bigint NOT NULL REFERENCES distcomp.tbl_stories(id),
    "tagId" bigint NOT NULL REFERENCES distcomp.tbl_tags(id)
);

DROP TABLE distcomp.tbl_stories_m2m_tags;
DROP TABLE distcomp.tbl_tags;
DROP TABLE distcomp.tbl_messages;
DROP TABLE distcomp.tbl_stories;
DROP TABLE distcomp.tbl_editors;
