@Forum.Api_HostAddress = http://localhost:5081

GET {{Forum.Api_HostAddress}}/weatherforecast/
Content-Type: application/json


{
    "login": "creator7619",
    "password": "asdfghj1006",
    "firstname": "firstname522",
    "lastname": "lastname6205"
}

###

