POST http://localhost:24110/api/v1.0/creators
Content-Type: application/json


{
    "login": "creator7619",
    "password": "asdfghj1006",
    "firstname": "firstname522",
    "lastname": "lastname6205"
}

