@DC_Lab1_HostAddress = http://localhost:24110

# GET {{DC_Lab1_HostAddress}}/weatherforecast/
# Accept: application/json

# GET {{DC_Lab1_HostAddress}}/api/v1.0/users/
# Accept: application/json


###